### ISSUE TITLE
chttpd_auth_cache changes listener died because the _users database does not exist

### ISSUE THREAD

**Issue by dnmrbughunter** [honoki/bbrf-server#12]
[notice] 2022-04-19T02:21:58.403323Z nonode@nohost <0.316.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
[error] 2022-04-19T02:21:58.404076Z nonode@nohost emulator -------- Error in process <0.904.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,374}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,96}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}

**Comment by honoki** [comment]
Hi - can you provide some more context around this error? What did you try to run? Where did you find the error?

**Comment by dnmrbughunter** [comment]
Sorry I had some errors with Docker and ubuntu Ubuntu 20.04.4 LTS, once fixed the Docker error everything is working. Thanks!
