### ISSUE TITLE
Nginx docker cannot load certificate /etc/nginx/keys/fullchain.pem

### ISSUE THREAD

**Issue by GiuBravo** [honoki/bbrf-server#14]
```
cat ~/.bbrf/config.json | grep "ignore_ssl_errors"
```
"ignore_ssl_errors": true

```
docker-compose logs proxy
```
proxy_1    | 2022/08/30 19:35:29 [emerg] 1#1: cannot load certificate "/etc/nginx/keys/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/keys/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
proxy_1    | nginx: [emerg] cannot load certificate "/etc/nginx/keys/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/keys/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

```
bbrf new myprogram
```
[ERROR] HTTPSConnectionPool(host='<My IP>', port=443): Max retries exceeded with url: /bbrf/<myprogram> (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3cddc237b8>: Failed to establish a new connection: [Errno 111] Connection refused',))

```
docker-compose ps
```
        Name                       Command               State               Ports            
----------------------------------------------------------------------------------------------
bbrf-server_couchdb_1   tini -- /docker-entrypoint ...   Up       4369/tcp, 5984/tcp, 9100/tcp
bbrf-server_proxy_1     nginx -g daemon off;             Exit 1

**Comment by honoki** [comment]
Did you follow the installation instructions and generate a valid certificate? Make sure to follow the steps of "[Generate certificate with Letsencrypt](https://github.com/honoki/bbrf-server#generate-certificate-with-letsencrypt)" closely, as the following step should make sure this error doesn't occur.

> Copy the generated certificate files to the keys volume: cp /etc/letsencrypt/live/yourdomain.com/{fullchain.pem,privkey.pem} ./proxy/keys/

Closing this, let me know if that doesn't resolve your issue.
